### ISSUE TITLE
Unable to get setup.ini

### ISSUE THREAD

**Issue by bikbajwa** [rylarson/chef-cygwin#5]
I am running into the following problem when I try to run this cookbook:

```
get_url_to_membuf http://mirrors.kernel.org/sourceware/cygwin/x86_64/setup.ini.sig
getUrlToStream http://mirrors.kernel.org/sourceware/cygwin/x86_64/setup.ini.sig
getUrlToStream failed!
get_url_to_membuf failed!
mbox note: Unable to get setup.ini from <http://mirrors.kernel.org/sourceware/cygwin/>
unattended_mode is set at mbox: returning default value
download/verify error in unattended_mode: out of retries
note: Installation incomplete.  Check C:\cygwin\var\log\setup.log.full for details
Ending cygwin install
STDERR:
---- End output of setup.exe -q -O -R C:/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ --proxy http://proxy.aus
tin.hp.com:8080 ----
Ran setup.exe -q -O -R C:/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ --proxy http://proxy.austin.hp.com:8080
 returned 1
```

Does anyone know how to resovle this?

**Comment by rylarson** [comment]
Hey @bikbajwa, 

The cygwin mirrors are pretty unreliable, sometimes it takes some trial and error to find one that works. You can set the cygwin mirror using the attribute `['cygwin']['site']`

Let me know if you have any problems doing this.

**Comment by bikbajwa** [comment]
@rylarson thanks. I tried a different mirror and re-ran a few times and it was successful. I would, however, like to find a way to get this working consistently.

**Comment by rylarson** [comment]
We are kind of at the mercy of the cygwin mirrors on this one, we can change the default but then that one will likely get flaky someday and we will be in the same position :).

I suppose we could build some sort of a retry mechanism in, but that might get pretty hairy.

**Comment by bikbajwa** [comment]
haha good point. I think I resolved this issue by using a "local-install" method, but that will only work if someone has the local install files necessary for Cygwin.
